### ISSUE TITLE
Settings lost for Omada Controller everytime Hassio reboots

### ISSUE THREAD

**Issue by al3x1337** [MattFryer/Hassio-Addons#1]
I've had Omada Controller running on Portainer before I found this amazing addon. Every since I cleaned up un-used images and volumes on Portainer, every reboot of Hassio my Omada configuration from this addon is deleted. I've already reinstalled Portainer and this addon without success.

The log doesn't show any useful information:

> ```INFO: Time zone set to 'America/Toronto'
> INFO: Starting Omada Controller as user omada
> tail: cannot open '/opt/tplink/EAPController/logs/server.log' for reading: No such file or directory
> tail: '/opt/tplink/EAPController/logs/server.log' has appeared;  following new file
> 2021-11-21 22:14:36 [log4j-thread] [INFO]-[SourceFile:29] - success to load configuration omada.properties
> 2021-11-21 22:14:39 [main] [INFO]-[SourceFile:91] - going to start local mongod.
> 2021-11-21 22:14:42 [main] [INFO]-[SourceFile:167] - mongodb process id is 43
> 2021-11-21 22:14:42 [main] [INFO]-[SourceFile:148] - Mongo DB server started
> 2021-11-21 22:15:41 [main] [INFO]-[SourceFile:193] - User do not configure max.device, use defaultValue 1500.
> 2021-11-21 22:15:56 [main] [INFO]-[SourceFile:38] - monitor context initialing...
> 2021-11-21 22:15:58 [main] [INFO]-[SourceFile:193] - User do not configure max.device, use defaultValue 1500.
> 2021-11-21 22:15:59 [main] [INFO]-[SourceFile:193] - User do not configure max.device, use defaultValue 1500.
> 2021-11-21 22:16:04 [main] [INFO]-[SourceFile:463] - restart all customize tasks.
> 2021-11-21 22:16:04 [main] [INFO]-[SourceFile:471] - GeneralSetting not exist?may be quick setup unfinished. Skip Global Dst Job.
> 2021-11-21 22:16:04 [main] [INFO]-[SourceFile:73] - DisconnectRequestServer start
> 2021-11-21 22:16:10 [device-discovery-server] [INFO]-[SourceFile:59] - Start device discovery server
> 2021-11-21 22:16:10 [device-manage-server] [INFO]-[SourceFile:116] - Start device manage server
> 2021-11-21 22:16:10 [device-adopt-server] [INFO]-[SourceFile:87] - Start device adopt server
> 2021-11-21 22:16:12 [main] [INFO]-[SourceFile:152] - no need to compatible db.
> 2021-11-21 22:16:12 [main] [INFO]-[SourceFile:20] - Omada Controller started
> 2021-11-21 22:16:12 [site-event-bus-0] [INFO]-[SourceFile:107] - Success sending config to devices.
> 2021-11-21 22:16:12 [site-event-bus-0] [WARN]-[SourceFile:439] - restart hotspot task failed, site : Default, timeZone : null
> 2021-11-21 22:16:19 [qtp809300666-76] [WARN]-[HttpChannel.java:593] - /modules/settings/maintenance/models-e8ebc4bd54.js java.io.IOException: Close org.eclipse.jetty.server.HttpConnection$SendCallback@345430f0[PROCESSING][i=null,cb=org.eclipse.jetty.server.HttpChannel$SendCallback@5fa91883] in state PROCESSING```

**Comment by koenvangils** [comment]
I have the same problem. Seems to be related to not using persistent storage.

**Comment by MattFryer** [comment]
This was an issue with having not having created the add on correctly from the Docker image. Hopefully this is now fixed. Let me know if you still have issues.
