### ISSUE TITLE
Not working on new HA version

### ISSUE THREAD

**Issue by MattScopes** [MattFryer/Hassio-Addons#10]
Not sure if this is still an active project, but I've been using this add-on for a while and it recently stopped working after a few updates of HA, giving me this error:
INFO: Time zone set to 'America/New_York'
INFO: Starting Omada Controller as user omada
tail: cannot open '/opt/tplink/EAPController/logs/server.log' for reading: No such file or directory
tail: '/opt/tplink/EAPController/logs/server.log' has appeared;  following new file
2023-02-08 21:03:30 [log4j-thread] [INFO]-[SourceFile:29] - success to load configuration omada.properties
2023-02-08 21:03:31 [main] [INFO]-[SourceFile:91] - going to start local mongod.
2023-02-08 21:04:01 [main] [ERROR]-[SourceFile:115] - Failed to delete old mongod.lock, exit starting mongod
2023-02-08 21:04:03 [main] [WARN]-[SourceFile:239] - Failed to stop mongod, pid is null
2023-02-08 21:04:33 [main] [ERROR]-[SourceFile:273] - Failed to delete old mongod.lock, exit repair mongod

I reinstalled and get this error:
INFO: Time zone set to 'America/New_York'
INFO: Omanda Controller directory missing; creating '/data/omada_controller'
done
WARNING: owner or group (0:0) not set correctly on '/opt/tplink/EAPController/work'
INFO: setting correct permissions
WARNING: owner or group (0:0) not set correctly on '/opt/tplink/EAPController/logs'
INFO: setting correct permissions
INFO: Database directory missing; creating '/data/omada_controller/data'
done
INFO: Starting Omada Controller as user omada
error: failed switching to "omada": unable to find user omada: no matching entries in passwd file
error: failed switching to "omada": unable to find user omada: no matching entries in passwd file

After some searching, seems like others are experiencing the same issue on recent versions:
https://community.home-assistant.io/t/hass-tp-link-omada-integration/286918/9

**Comment by RalfAlbers** [comment]
use the Omada Addon from https://github.com/alexbelgium/hassio-addons
That's active and working
