### ISSUE TITLE
amd64 support

### ISSUE THREAD

**Issue by DerOrakel** [MattFryer/Hassio-Addons#2]
Hi, I would really like to run this on my nuc as I just got my first EAP, so I would really appreciate support for amd64 architecture.

**Comment by Fokkie** [comment]
+1

**Comment by MattFryer** [comment]
Should now support amd64. I don't have a device to test it on through so give it a try and let me know if it works OK

**Comment by deku-m** [comment]
Hi Matt,

I tried your install on amd64 but it fails for me:
`The command '/bin/sh -c chmod +x /*.sh' returned a non-zero code: 1`

Tried to install 0.2.0

**Comment by MattFryer** [comment]
Hi, I found an issue in the dockerfile which I'm hoping might fix it. Not having the hardware I can't test myself so let me know if this fix worked?

New version with the fix should be 0.2.1

**Comment by deku-m** [comment]
Install is fixed but running is still a issue:

```
INFO: Time zone set to 'Europe/Amsterdam'
/entrypoint.sh: 134: /entrypoint.sh: Syntax error: "fi" unexpected (expecting "then")
```

**Comment by MattFryer** [comment]
Can you try version 0.2.2 just released?

**Comment by deku-m** [comment]
It is up and running :) thanks

**Comment by MattFryer** [comment]
Great!
